# Generated by Django 4.1.3 on 2023-01-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
